name: build kernel via commit

on:
  workflow_dispatch:
    inputs:
      Device:
        type: choice
        description: Device
        required: true
        options: 
        - a51
        - m30s
        - m21
        - m31
        - m31s
        - f41
      myCommit:
        description: 'Commit SHA1'
        required: true
        default: 'undefined'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - device: a51
          - device: m30s
          - device: m21
          - device: m31
          - device: m31s
          - device: f41
    name: "🚧 Build for ${{matrix.device}}"
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{inputs.myCommit}}
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update
          bash <(curl https://gist.githubusercontent.com/roynatech2544/0feeeb35a6d1782b186990ff2a0b3657/raw/b170134a94dac3594df506716bc7b802add2724b/setup.sh)
          sudo apt install bison flex libssl-dev
          cp local.config.sample local.config
          sed -i '/CONFIG_THINLTO/d' arch/arm64/configs/vendor/grass.config
          echo "OBJ=arch/arm64/boot/Image" >> local.config

      - name: Run build
        run: |
          DEVICE=${{inputs.Device}} bash build_kernel.sh

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: GrassKernel_${{matrix.device}}.zip
          path: scripts/packaging/Grass*

